title: Aster Documentation
description: The documentation for the Aster project.
theme: just-the-docs

color_scheme: aster

logo:  "/assets/images/aster_logo_docs2.svg"
favicon_ico: "/assets/images/aster_logo.svg"